# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Raio1Km
                                 A QGIS plugin
 Cria Raio de 1 km da ANM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-24
        copyright            : (C) 2023 by Romário Moraes Carvalho Neto
        email                : romariocarvalho@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Raio1Km class from file Raio1Km.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raio1km import Raio1Km
    return Raio1Km(iface)
